---
# Can be "stable" or "test". Note that stable patches
# requires authentication to download. See the grsecurity
# blog for more information:
# https://grsecurity.net/announce.php
grsecurity_patch_type: test

# Declaring a list of supported distributions
# for package dependency lists. Role will fail
# if playbook attempts to compile under a different OS,
# with a helpful message soliciting a PR. =)
supported_linux_distributions:
  - Debian
  - Ubuntu

download_directory: /usr/src
linux_kernel_version: linux-3.14.52

linux_tarball:
  {
    filename: "{{ linux_kernel_version }}.tar.xz",
    url: "https://www.kernel.org/pub/linux/kernel/v3.x/{{ linux_kernel_version }}.tar.xz",
    sha256sum: 1bba61c76fdabb4a707832fd0eeecbf98a2ac149864442005004378ed2edf2e9,
  }

linux_tarball_signature:
  {
    filename: "{{ linux_kernel_version }}.tar.sign",
    url: "https://www.kernel.org/pub/linux/kernel/v3.x/{{ linux_kernel_version }}.tar.sign",
    sha256sum: 66c043ae1751da05f355e9089c0056085aebf05f788c6450187e2b05d3e48948,
  }

grsecurity_patch:
  {
    filename: grsecurity-3.1-3.14.49-201508032312.patch,
    url: 'https://grsecurity.net/stable/grsecurity-3.1-3.14.49-201508032312.patch',
    sha256sum: 4cdaa8464a66433bbb38e3e5c1f25f6351ae20a7a7fca6cd65f0d577c9caa027,
  }

grsecurity_patch_signature:
  {
    filename: grsecurity-3.1-3.14.49-201508032312.patch.sig,
    url: 'https://grsecurity.net/stable/grsecurity-3.1-3.14.49-201508032312.patch.sig',
    sha256sum: d0a72f991e93d27cbd48760f0bca4d5968784936cf6c44e0292c0a3bdcb3454e,
  }

required_kernel_files:
  - "{{ linux_tarball }}"
  - "{{ linux_tarball_signature }}"
  - "{{ grsecurity_patch }}"
  - "{{ grsecurity_patch_signature }}"
