---
# Can be "stable" or "test". Note that stable patches
# requires authentication to download. See the grsecurity
# blog for more information:
# https://grsecurity.net/announce.php
grsecurity_patch_type: test

download_directory: /usr/src
linux_version: linux-3.14.51

linux_tarball:
  {
    filename: linux-3.14.51.tar.xz,
    url: "https://www.kernel.org/pub/linux/kernel/v3.x/linux-3.14.51.tar.xz",
    sha256sum: b306bc95cab19be0b77b356fe33d6846082a596d9ee44518714e46cc92691abf,
  }

linux_tarball_signature:
  {
    filename: linux-3.14.51.tar.sign,
    url: "https://www.kernel.org/pub/linux/kernel/v3.x/linux-3.14.51.tar.sign",
    sha256sum: c4bbe53fae6a4fe2dfd7ec2a0fc66daa7762fa53a94ce4ffb26b537d6bac489e,
  }

required_kernel_files:
  - "{{ linux_tarball }}"
  - "{{ linux_tarball_signature }}"
  - "{{ grsecurity_patch }}"
  - "{{ grsecurity_patch_signature }}"
