---
download_directory: /usr/src
linux_version: linux-3.14.51

linux_tarball:
  {
    filename: linux-3.14.51.tar.xz,
    url: "https://www.kernel.org/pub/linux/kernel/v3.x/linux-3.14.51.tar.xz",
    sha256sum: b306bc95cab19be0b77b356fe33d6846082a596d9ee44518714e46cc92691abf,
  }

linux_tarball_signature:
  {
    filename: linux-3.14.51.tar.sign,
    url: "https://www.kernel.org/pub/linux/kernel/v3.x/linux-3.14.51.tar.sign",
    sha256sum: c4bbe53fae6a4fe2dfd7ec2a0fc66daa7762fa53a94ce4ffb26b537d6bac489e,
  }

grsecurity_patch:
  {
    filename: grsecurity-3.1-3.14.51-201508181951.patch,
    url: 'https://grsecurity.net/stable/grsecurity-3.1-3.14.51-201508181951.patch',
    sha256sum: ce44e5f6c158deae8673772c18fa2f362f25ca5ba12caf0ea6ee4375147fe1ea,
  }

grsecurity_patch_signature:
  {
    filename: grsecurity-3.1-3.14.51-201508181951.patch.sig,
    url: 'https://grsecurity.net/stable/grsecurity-3.1-3.14.51-201508181951.patch.sig',
    sha256sum: 9ac36e5f5b2b60ec7e7951387741a021b00184263e0e36a51bd97b1c60306d34,
  }

required_kernel_files:
  - "{{linux_tarball}}"
  - "{{linux_tarball_signature}}"
  - "{{grsecurity_patch}}"
  - "{{grsecurity_patch_signature}}"
