---
- name: Build the grsecurity-patched kernel.
  command: fakeroot make-kpkg --initrd kernel_image
  args:
    chdir: "{{ linux_source_directory }}"
  environment:
    CONCURRENCY_LEVEL: "{{ ansible_processor_vcpus }}"
    # Conditionally enable ccache by prepending the ccache lib directory
    # to PATH, which will override the system gcc and and g++ binaries.
    PATH: "{% if grsecurity_use_ccache == true %}/usr/lib/ccache:{% endif %}{{ ansible_env.PATH }}"
  when: grsecurity_build_strategy != 'ubuntu'

- name: Build the grsecurity-patched kernel with Ubuntu overlay files.
  command: fakeroot make-kpkg --initrd --overlay-dir=../ubuntu-package kernel_image
  args:
    chdir: "{{ linux_source_directory }}"
  environment:
    CONCURRENCY_LEVEL: "{{ ansible_processor_vcpus }}"
    PATH: "{% if grsecurity_use_ccache == true %}/usr/lib/ccache:{% endif %}{{ ansible_env.PATH }}"
  when: grsecurity_build_strategy == 'ubuntu'

- name: Fetch built kernel package back to localhost.
  fetch:
    src: "{{ download_directory }}/{{ grsecurity_deb_package }}"
    dest: ./
    fail_on_missing: yes
    flat: yes
  tags:
    - fetch
