---
- name: extract linux tarball
  command: tar -xf {{linux_tarball.filename}}
  args:
    chdir: "{{download_directory}}"
    creates: "{{download_directory}}/{{linux_version}}"

- name: apply grsecurity patch
  shell: patch -p1 < ../{{grsecurity_patch.filename}}
  args:
    chdir: "{{download_directory}}/{{linux_version}}"

- name: put kernel config
  template:
    src: config
    dest: "{{download_directory}}/{{linux_version}}/.config"

- name: clean kernel source tree
  shell: cd {{download_directory}}/{{linux_version}} && make-kpkg clean

- name: build the kernel
  shell: cd {{download_directory}}/{{linux_version}} && make-kpkg --initrd kernel_image kernel_headers
