---
- name: clone ubuntu overlay git repository (slow!)
  git:
    repo: git://kernel.ubuntu.com/ubuntu/ubuntu-trusty.git
    dest: "{{ download_directory }}/ubuntu-trusty"
    force: yes
    # since this clone takes a long time, just grab
    # the first layer. can then pull manually to update.
    depth: 1
    # definitely don't want to do this, but only
    # other option is scanning kernel.ubuntu.com
    # and accepting whatever is returned
    accept_hostkey: yes
  tags:
    - git

- name: copy kernel package files
  shell: cp -a /usr/share/kernel-package {{ download_directory }}/ubuntu-package
  args:
    creates: "{{ download_directory }}/ubuntu-package"

- name: copy ubuntu overlay control files
  shell: >
     cp {{ download_directory }}/ubuntu-trusty/debian/control-scripts/p* \
        {{ download_directory }}/ubuntu-package/pkg/image/

- name: copy ubuntu overlay header files
  command: >
     cp {{ download_directory }}/ubuntu-trusty/debian/control-scripts/headers-postinst \
        {{ download_directory }}/ubuntu-package/pkg/headers/
