---
- name: Create directory for downloaded files.
  file:
    state: directory
    dest: "{{ download_directory  }}"

- name: Fetch SHA256 checksums for Linux source files.
  get_url:
    url: "{{ linux_checksums_url }}"
    dest: "{{ download_directory }}"
  register: linux_source_checksums

- name: Read checksum for kernel tarball.
  shell: >
    grep {{ linux_tarball.filename }}
    {{ linux_checksums.dest }} | cut -d' ' -f1
  changed_when: false
  register: linux_tarball_checksum

- name: Fetch Linux kernel tarball.
  get_url:
      url: "{{ linux_tarball.url  }}"
      dest: "{{ download_directory }}/{{ linux_tarball.filename }}"
      sha256sum: "{{ linux_tarball_checksum.stdout }}"

- name: Fetch Linux kernel tarball signature file.
  get_url:
      url: "{{ linux_tarball.signature  }}"
      dest: "{{ download_directory }}"
