---
- include: packages.yml

- include: fetch_files.yml

- include: fetch_grsecurity_files.yml

- include: fetch_ubuntu_overlay.yml
  when: 'target_os == "ubuntu"'

- include: verify.yml
- include: compile.yml
- include: copy.yml
