---
- include: packages.yml

- include: fetch_linux_kernel_source.yml

- include: fetch_grsecurity_files.yml

- include: fetch_ubuntu_overlay.yml
  when: 'target_os == "ubuntu"'

- include: gpg_keys.yml
- include: verify.yml
- include: compile.yml
- include: copy.yml
