---
- name: Include grsecurity download URLs.
  include_vars: grsecurity_{{ grsecurity_patch_type }}_patches.yml
  # Setting task to "always" run, because other tasks will
  # without the imported vars. Usually defaults would handle ensuring
  # vars aren't missing, but we're conditionally including vars.
  tags:
    - always

- include: packages.yml

- include: gpg_keys.yml

- include: fetch_linux_kernel_source.yml

- include: fetch_grsecurity_files.yml

- include: fetch_ubuntu_overlay.yml
  when: grsecurity_build_strategy == "ubuntu"

- include: verify.yml

- include: ccache.yml
  when: grsecurity_use_ccache == true

- include: configure.yml tags=configure

- include: compile.yml tags=compile
