---
- name: install required packages for building kernel on Debian
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - libncurses5-dev
    - build-essential
    - kernel-package
    - gcc-4.9
    - gcc-4.9-plugin-dev
    - make
  when: target_os == 'debian'

- name: install required packages for building kernel on Ubuntu
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - libncurses5-dev
    - build-essential
    - kernel-package
    - gcc-4.8
    - gcc-4.8-plugin-dev
    - git-core
    - make
  when: target_os == 'ubuntu'
