---
- name: Extract Linux tarball.
  command: unxz {{ download_directory }}/{{ linux_tarball.filename }}
  args:
    creates: "{{ download_directory }}/{{ linux_tarball.filename|regex_replace('(.*)\\.xz$', '\\\\1') }}"

- name: Verify Linux tarball GPG signature.
  command: gpg --verify {{ download_directory }}/{{ linux_tarball_signature.filename }}
  changed_when: false

- name: Verify grsecurity patch GPG signature.
  command: gpg --verify {{ download_directory }}/{{ grsecurity_patch_signature.filename }}
  changed_when: false

- name: Register current release tag for Ubuntu overlay.
  command: git tag
  args:
    chdir: "{{ download_directory }}/ubuntu-trusty"
  register: ubuntu_overlay_tag_result
  changed_when: false
  when: target_os == 'ubuntu'

- name: Verify Ubuntu overlay signature.
  command: git tag --verify {{ ubuntu_overlay_tag_result.stdout }}
  args:
    chdir: "{{ download_directory }}/ubuntu-trusty"
  changed_when: false
  when: target_os == 'ubuntu'
