---
- name: Install grsecurity-patched kernel deb package.
  hosts: grsec-install
  roles:
    - role: install-grsec-kernel
      # Add the filepath to the .deb package here. The playbook will error out
      # if the package can't be found.
      #grsecurity_install_deb_package: ''
  become: yes
