---
- name: Make the required grub paxctl changes.
  command: paxctl -Cpm {{ item }}
  with_items:
    - /usr/sbin/grub-probe
    - /usr/sbin/grub-mkdevicemap
    - /usr/bin/grub-script-check
    - /usr/bin/grub-mount

- name: Find the menu title for the grsecurity kernel in GRUB config.
  set_fact:
    grub_grsecurity_menu_entry: "{{ item }}"
  with_items: grub_menu_options
  when: "{{ item.name | match('.*-grsec$') }}"

- name: Ensure grsecurity kernel menu entry is populated.
  fail:
    msg: >
      Could not find GRUB menu entry for grsecurity kernel.
  when: grub_grsecurity_menu_entry is not defined

- name: Set grsecurity kernel as default option in GRUB config.
  sudo: yes
  lineinfile:
    regexp: '^GRUB_DEFAULT='
    # Conditional logic necessary for Debian because running `update-grub`
    # without the specific prefix results in a warning:

    #   Warning: Please don't use old title `Debian GNU/Linux, with
    #   Linux 3.14.53-grsec' for GRUB_DEFAULT, use `Advanced
    #   options for Debian GNU/Linux>Debian GNU/Linux, with Linux
    #   3.14.53-grsec' (for versions before 2.00) or
    #   `gnulinux-advanced-fc2b679a-e448-4f54-b465-62735483f42f>gnul
    #   inux-3.14.53-grsec-advanced-fc2b679a-e448-4f54-b465-62735483
    #   f42f' (for 2.00 or later)
    line: 'GRUB_DEFAULT="{% if ansible_distribution == "Debian" %}Advanced options for Debian GNU/Linux>{% endif %}{{ grub_grsecurity_menu_entry.name }}"'
    dest: /etc/default/grub
  notify:
    - Update GRUB.
    - Update host facts.

  # Force handlers to run immediatley, so grub config is updated.
- meta: flush_handlers
