---
- name: Make the required grub paxctl changes.
  command: paxctl -Cpm {{ item }}
  with_items: grub_pax

- name: Get grsecurity kernel string for grub menu.
  shell: grep menuentry /boot/grub/grub.cfg | grep grsec | grep -v recovery | head -1 | cut -d "'" -f2
  register: grsec_str

- name: Set newly installed grsecurity kernel as default boot option in GRUB.
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_DEFAULT='
    state: present
    # TODO: We're assuming that "vanilla" == "Debian" here.
    # We need a smarter way to set the line, possibly via backrefs
    # in the regex matching.
    line: 'GRUB_DEFAULT="Advanced options for {% if grsecurity_build_strategy == "ubuntu" %}Ubuntu{% else %}Debian GNU/Linux{% endif %}>{{ grsec_str.stdout }}"'

- name: Update GRUB menu information.
  command: update-grub
  when: "'grsec' not in uname_initial_result.stdout"

- name: Set grsecurity kernel as default option for next boot.
  # TODO: We're assuming that "vanilla" == "Debian" here.
  # We need a smarter way to set the line, possibly via backrefs
  # in the regex matching.
  command: grub-reboot "Advanced options for {% if grsecurity_build_strategy == "ubuntu" %}Ubuntu{% else %}Debian GNU/Linux{% endif %}>{{ grsec_str.stdout }}"
  when: "'grsec' not in uname_initial_result.stdout"

