---
- name: Make the required grub paxctl changes.
  command: paxctl -Cpm {{ item }}
  with_items: grub_pax

- name: Find the menu title for the grsecurity kernel in GRUB config.
  set_fact:
    grub_grsecurity_menu_entry: "{{ item }}"
  with_items: grub_menu_options
  when: "{{ item.name | match('.*-grsec$') }}"

- name: Ensure grsecurity kernel menu entry is populated.
  fail:
    msg: >
      Could not find GRUB menu entry for grsecurity kernel.
  when: grub_grsecurity_menu_entry is not defined

- name: Set grsecurity kernel as default option in GRUB config.
  sudo: yes
  lineinfile:
    regexp: '^GRUB_DEFAULT='
    line: 'GRUB_DEFAULT="{{ grub_grsecurity_menu_entry.name }}"'
    dest: /etc/default/grub
  notify:
    - Update GRUB.
    - Update host facts.

  # Force handlers to run immediatley, so grub config is updated.
- meta: flush_handlers
