---
- include: set_host_facts.yml
- include: packages.yml

- name: Check whether grsecurity is already running.
  command: uname -r
  register: uname_initial_result
  changed_when: false

- include: disable_python_memprotect.yml
  when: ansible_distribution == "Debian" and
        grsec_disable_python_memprotect is defined and
        grsec_disable_python_memprotect == "true"

- include: grub_config.yml

- name: Reboot into the grsecurity kernel.
  # Simply rebooting causes the subsequent wait_for task to fail. See here:
  # https://github.com/ansible/ansible/issues/10616
  # Sleeping and then shutting down, via the shell module, is a workaround.
  shell: sleep 3 && shutdown -r now "Rebooting into the grsec kernel..."
  async: 1
  poll: 0
  ignore_errors: true
  sudo: yes
  when: "'grsec' not in uname_initial_result.stdout"

- name: Wait for server to come back.
  local_action: wait_for
    host={{ ansible_ssh_host }}
    port={{ ansible_ssh_port | default('22')}}
    delay=30
    state=started
  sudo: false
  when: "'grsec' not in uname_initial_result.stdout"

  # Adding extra wait time to prevent timeouts
  # during debugging. Likely not necessary, but test
  # before removing.
- name: Wait extra time for server to come back up.
  pause:
    seconds: 30
  when: "'grsec' not in uname_initial_result.stdout"

- name: Check that grsecurity kernel is running.
  command: uname -r
  register: uname_final_result
  changed_when: false
  failed_when: "'grsec' not in uname_final_result.stdout"

