---
- name: copy kernel package to destination server
  copy: src={{package_filename}} dest=/root/{{package_filename}}

- name: install paxctl
  apt: pkg=paxctl state=present

- name: install paxtest
  apt: pkg=paxtest state=present

- name: make the required grub paxctl changes
  command: paxctl -Cpm {{ item }}
  with_items: grub_pax

- name: install grsec kernel
  apt: deb="/root/{{package_filename}}"

- name: get grsec kernel string
  shell: grep menuentry /boot/grub/grub.cfg | grep grsec | grep -v recovery | head -1 | cut -d "'" -f2
  register: grsec_str

- name: set grsec kernel as default for next boot
  command: grub-reboot "Advanced options for Debian GNU/Linux>{{ grsec_str.stdout }}"

- name: reboot into the grsec kernel
  command: shutdown -r now "Rebooting into the grsec kernel..."
  async: 0
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  local_action:
    module: wait_for
      host={{ ansible_ssh_host }}
      port={{ ansible_ssh_port }}
      delay=60
      state=started

- name: set sysctl flags for grsecurity
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items: grsec_sysctl_flags
  sudo: yes
