---
- vars:
  package_fileame: linux-image-3.14.51-grsec_3.14.51-grsec-10.00.Custom_amd64.deb

#- hosts: grsec-build

#  roles:
#    - { role: build-grsec-kernel }

#  sudo: yes

- hosts: grsec-install

  roles:
    - { role: install-grsec-kernel }

