---
- name: Install grsecurity-patched kernel deb package.
  hosts: grsec-install
  roles:
    - { role: install-grsec-kernel,
        grsecurity_deb_package: linux-image-3.14.53-grsec_3.14.53-grsec-10.00.Custom_amd64.deb,
      }
  sudo: yes
  vars_files:
    - vars.yml
