---
- name: Create parent build directory.
  file:
    state: directory
    path: "{{ grsec_build_parent_directory }}"

- name: Clean build subdirectory.
  file:
    state: absent
    path: "{{ grsec_build_directory }}"

- name: Create build subdirectory.
  file:
    state: directory
    path: "{{ grsec_build_directory }}/DEBIAN"

- name: Copy DEBIAN control file.
  template:
    src: control
    path: "{{ grsec_build_directory }}/DEBIAN/control"

- name: Build the Debian package.
  command: dpkg-deb --build {{ grsec_build_directory }}

