---
# fetch required kernel packages for compilation
- name: fetch linux kernel and grsecurity patches
  get_url:
      url: "{{item.url}}"
      dest: "{{download_directory}}/{{item.filename}}"
      sha256sum: "{{item.sha256sum}}"
  with_items: required_kernel_files
    
- name: clone ubuntu overlay git repository (slow!)
  git:
    repo: git://kernel.ubuntu.com/ubuntu/ubuntu-trusty.git
    dest: "{{download_directory}}/ubuntu-trusty"
    force: yes


